import { Header } from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TabBar from "@/components/TabBar";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + "w-full h-screen"}>
        <Providers>
          <Header />
          <main className="mx-auto flex h-screen w-full flex-col items-center gap-[20px] md:gap-[40px]">
            {children}
          </main>
          <TabBar />
        </Providers>
      </body>
    </html>
  );
}
